name: Build and Release Rust Binaries

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags, e.g., v1.0.0

env:
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  build:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          # - target: x86_64-apple-darwin
          #   archive: zip
    steps:
      - uses: actions/checkout@main
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
      - name: List files
        run: |
          ls
          ls /github/workspace/output
        continue-on-error: true
      - name: Compress binaries
        run: |
          zip rust-binary-${{ matrix.target }}.zip /github/workspace/output/*
  
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust-binary-${{ matrix.target }}
          path: rust-binary-${{ matrix.target }}.zip
  release:
    name: Create Release
    permissions: write-all
    needs: build
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: rust-binary-${{ matrix.target }}
          # path: rust-binary-${{ matrix.target }}.zip # Should exist
      - name: list-artifacts
        run: ls
      - name: Create GitHub Release
        uses: 'softprops/action-gh-release@v1'
        with:
          files: |
              rust-binary-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
