name: Build and Release Rust Binaries

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags, e.g., v1.0.0

env:
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            artifacts/rust-binary-x86_64-unknown-linux-gnu.zip
            artifacts/rust-binary-x86_64-pc-windows-gnu.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release contains pre-built binaries for the following platforms:
            - Linux (x86_64-unknown-linux-gnu)
            - Windows (x86_64-pc-windows-gnu)
